blank_issues_enabled: false
contact_links:
    - name: GitHub Discussions
      url:  https://github.com/Polprzewodnikowy/SummerCart64/discussions
      about: Please use for QUESTIONS, conversations or discussions.
    - name: N64Brew Discord
      url: https://discord.gg/8xvRPqCAFC
      about: Alternative channel for asking QUESTIONS.
